<a href="https://colab.research.google.com/github/saakshe/titanic-/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data preprocessing

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [ ]:
X = dataset.iloc[:, 2:].values
y = dataset.iloc[:, 1].values
X_test = test.iloc[:, 1:].values
print(X_test)

[[3 'Kelly, Mr. James' 'male' ... 7.8292 nan 'Q']
 [3 'Wilkes, Mrs. James (Ellen Needs)' 'female' ... 7.0 nan 'S']
 [2 'Myles, Mr. Thomas Francis' 'male' ... 9.6875 nan 'Q']
 ...
 [3 'Saether, Mr. Simon Sivertsen' 'male' ... 7.25 nan 'S']
 [3 'Ware, Mr. Frederick' 'male' ... 8.05 nan 'S']
 [3 'Peter, Master. Michael J' 'male' ... 22.3583 nan 'C']]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X[:, 3:4] = imputer.fit_transform(X[:, 3:4])
X_test[:, 3:4] = imputer.fit_transform(X_test[:, 3:4])

In [ ]:
print(X.shape[1])
print(X_test.shape[1])

10
10


In [ ]:
X = np.delete(X, [1,6,7,8, 9], axis=1)
X_test = np.delete(X_test, [1,6,7,8, 9], axis=1)
print(X_test)

[[3 'male' 34.5 0 0]
 [3 'female' 47.0 1 0]
 [2 'male' 62.0 0 0]
 ...
 [3 'male' 38.5 0 0]
 [3 'male' 30.272590361445783 0 0]
 [3 'male' 30.272590361445783 1 1]]


In [ ]:
print(X)

[[3 'male' 22.0 1 0]
 [1 'female' 38.0 1 0]
 [3 'female' 26.0 0 0]
 ...
 [3 'female' 29.69911764705882 1 2]
 [1 'male' 26.0 0 0]
 [3 'male' 32.0 0 0]]


In [ ]:
print(X.shape[1])
print(X_test.shape[1])

5
5


Categorical data 

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X_test = np.array(ct.fit_transform(X_test))

In [ ]:
# ft = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [])], remainder='passthrough')
# X = np.array(ft.fit_transform(X))
# X_test = np.array(ft.fit_transform(X_test))

In [ ]:
print(X)
print(X.shape[1])

[[0.0 1.0 3 22.0 1 0]
 [1.0 0.0 1 38.0 1 0]
 [1.0 0.0 3 26.0 0 0]
 ...
 [1.0 0.0 3 29.69911764705882 1 2]
 [0.0 1.0 1 26.0 0 0]
 [0.0 1.0 3 32.0 0 0]]
6


In [ ]:
print(X_test)
print(X_test.shape[1])

[[0.0 1.0 3 34.5 0 0]
 [1.0 0.0 3 47.0 1 0]
 [0.0 1.0 2 62.0 0 0]
 ...
 [0.0 1.0 3 38.5 0 0]
 [0.0 1.0 3 30.272590361445783 0 0]
 [0.0 1.0 3 30.272590361445783 1 1]]
6


Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X_test = sc.transform(X_test)

In [ ]:
print(X.shape[1])
print(X_test.shape[1])

6
6


KNN model

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
classifier.fit(X, y)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(X_test)
y_pred = y_pred.reshape(len(y_pred),1)
# y = y.reshape(len(y),1)
# y_pred = y_pred.reshape(len(y_pred),0)
# y = y.reshape(len(y),0)


In [ ]:
print(y_pred)

[[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]


In [ ]:
print(classifier.predict(sc.transform((X_test))))


[0 1 0 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0 1 1 0 1 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1
 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 0 1 1 0 1 0
 1 0 0 1 0 1 1 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0
 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1
 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 0 1 0 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 1 0
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0
 1 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0
 1 0 0 0 1 0 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0
 0 1 0 0 1 1 1 0 0 1 0 0 1 1 0 1 0 0 0 1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0
 1 1 1 1 1 1 0 1 0 0 1]


In [ ]:
# from google.colab import drive
# drive.mount('/drive')


In [ ]:
# y_pred.to_csv('data.csv')
# !cp data.csv "drive/My Drive/"

In [ ]:
from google.colab import files
df = pd.DataFrame(data = y_pred)
df.to_csv('output.csv', encoding = 'utf-8-sig') 
files.download('output.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>